name: wait_group
description: "A tiny, lightweight Dart implementation of Golang's WaitGroup for managing asynchronous tasks."
version: 1.0.0
homepage: https://github.com/nslogx/wait_group

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
